Alert fix
palashmunshi/Gatepass-Portal pull request #26
Opened 2023-03-16 18:06 UTC by palashmunshi

i have added separate alerts for the decline of local fixed gatepass.

2023-03-16 18:08 UTC, palashmunshi commented
Please check if the alert message written is fine or do i have to change.

2023-03-16 18:11 UTC, ayushSinha16 commented on client-side/src/Components/studentComponent/Gatepasses/LocalFixed/Form/LFform.js
> +        "Cannot Apply: You are not within the time limit of Local FIxed Gatepass"
1) The "I" in Fixed should be small
2) I think it would be better if "You cannot apply a gatepass in the outside hours"

2023-03-16 18:11 UTC, ayushSinha16 requested changes
Check line 158

2023-03-17 04:22 UTC, ayushSinha16 approved these changes
ok

2023-03-17 04:22 UTC, merged